### ISSUE TITLE
Can the name of the output file be formated too?

### ISSUE THREAD

**Issue by jrcacd** [davideas/GrabVer#1]
First I want to say, this project is very, very good.
Very easy to use, and very well designed.

Now, the question:
Can the name of the output file be formated too? 
For example to have the versioning.name variable content.
Ex: 1.1.0-RC1.apk

**Comment by davideas** [comment]
Thank you @jrcacd!
It can be perfectible, since I am not expert in Gradle.

This plugin can be used in non-android projects as well.
In Android do this:

``` gradle
defaultConfig {
    ...
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def file = output.outputFile
            def fileName = 'myfilename-v' + versioning.name + '-c' + versioning.code + '.apk'
            output.outputFile = new File(file.parentFile, fileName)
        }
    }
}
```

**Comment by jrcacd** [comment]
Ok, thanks

**Comment by davideas** [comment]
This code will work also with Android Studio 3:
``` gradle
android.applicationVariants.all { variant ->
    variant.outputs.all {
        outputFileName = "app-${variant.name}-${variant.versionName}-c${versioning.code}.apk"
    }
}
```
