### ISSUE TITLE
It there a way to set directly the patch number in gradle?

### ISSUE THREAD

**Issue by jrcacd** [davideas/GrabVer#11]
```
versioning {
    major = 2
    minor = 1
    patch = 7 //This part
}
```

The motive is that I have a list with the versions numbers, and respective changelog.
I want to set the major, minor and patch directelly from the last record os my list.

The GrabVer still need to update the build number

**Comment by davideas** [comment]
@jrcacd, it could be that if set by the user, there's no automatic increase? Ok, I will have a look.

**Comment by jrcacd** [comment]
Ok, yes.
