### ISSUE TITLE
Error in Execution please help me to solve this

### ISSUE THREAD

**Issue by ABKZR** [davideas/GrabVer#12]
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-vector-icons'.
      > Could not resolve all dependencies for configuration ':react-native-vector-icons:classpath'.
         > Could not resolve com.android.tools.build:gradle:2.3.+.
           Required by:
               Login_Page:react-native-vector-icons:unspecified
            > Could not resolve com.android.tools.build:gradle:2.3.+.
               > Failed to list versions for com.android.tools.build:gradle.
                  > Unable to load Maven meta-data from https://jcenter.bintray.com/com/android/tools/build/gradle/maven-metadata.xml.
                     > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/maven-metadata.xml'.
                        > Permission denied: connect

**Comment by davideas** [comment]
@ABKZR, sorry but this is not an issue related to this project.
