### ISSUE TITLE
Increase CODE number in release build with the new Android App Bundle

### ISSUE THREAD

**Issue by jrcacd** [davideas/GrabVer#14]
https://developer.android.com/guide/app-bundle/

**Comment by davideas** [comment]
@jrcacd, uhm, interesting mechanism for on demand feature from play store.
Well, of course it is a nice thing, but until I am not involved in it, this issue can stay opened. I mean I leave it as low priority.

**Comment by jrcacd** [comment]
I think it only needs to add this:
runTasks.contains("bundle") ||

**Comment by jrcacd** [comment]
Still not working...

**Comment by davideas** [comment]
@jrcacd, if you want it, try to find a way, since you are using the bundle :-)

**Comment by jrcacd** [comment]
Still not increasing the code.

I found that the `project.gradle.taskGraph` does not contain anything in bundle release, so the `project.gradle.taskGraph.afterTask { }` code block does not save the new code number to the file

**Comment by davideas** [comment]
@jrcacd, use `saveOn <task-name>` to save it.

**Comment by jrcacd** [comment]
Even if I indicate any task name in ` saveOn <task-name>` the new code number will not get saved to file because `project.gradle.taskGraph `is empty
