### ISSUE TITLE
android.defaultConfig.versionCode is set to 0, but it should be a positive integer.

### ISSUE THREAD

**Issue by wankey** [davideas/GrabVer#15]
I got a build failed when configuring project  after upgrade Android Studio to 3.3 canary 5 and android-gradle-plugin to 3.3.0-alpha 05
>A problem occurred configuring project ':app'.
 android.defaultConfig.versionCode is set to 0, but it should be a positive integer.
  See https://developer.android.com/studio/publish/versioning#appversioning for more information.

android studio version -> 3.3 canary 5
gradle version -> 4.9
android-gradle-plugin ->  3.3.0-alpha 05

build.gradle in app :
>versioning {
  // required (number)
  major = 1
  minor = 0
  // force patch, optional (number)
  patch = 0
  dependsOn = "install"
  // optional (any string)
  preRelease = 'SNAPSHOT'
}

>defaultConfig {
    minSdkVersion versions.minSdk
    targetSdkVersion versions.targetSdk
    versionCode versioning.code
    versionName versioning.name
    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
  }

**Comment by yaroslav-shlapak** [comment]
As a workaround try to hardcode version number or just versioning.code  + 1, then run one of "bundle", "grabverRelease", ":[module]:assembleRelease". You can then correct the numbers to anything you like in [module]/version.properties.

@davideas I've created more specific issue regarding this bug: https://github.com/davideas/GrabVer/issues/17

**Comment by davideas** [comment]
Thanks @wankey @yaroslav-shlapak.
Resolved by #17.
