### ISSUE TITLE
Error with subprojects

### ISSUE THREAD

**Issue by takvorian** [davideas/GrabVer#23]
Thanks for this great tool.

However I found an issue working with subprojects.
The path to the subproject is not determined correctly if a more complex project structure is used.
My project structure is similar to this:

ProjectA
ProjectA\SomeDir\ProjectB

It works correctly with ProjectA but as soon as I apply GrabVer to ProjectB it tries to create the version.properties in directory ProjectA\ProjectB which fails because the directory does of course not exist.

I think a solution could be to use Project's file(Object path) method because it resolves a file path relative to the project directory of the given project.

Greetings
Tak

**Comment by davideas** [comment]
@takvorian, thanks for writing.
I can fix with `project.projectDir.absolutePath`. Which simplifies the code as well. I hope it works for you.
