### ISSUE TITLE
Error: A problem occurred configuring project ':app'. (version 0.4.1)

### ISSUE THREAD

**Issue by jrcacd** [davideas/GrabVer#3]

**Comment by davideas** [comment]
@jrcacd, can you check the Gradle console (bottom right)?

**Comment by jrcacd** [comment]
The error ocurs when I click in "Sync Now" after set version from 0.4.0 to 0.4.1.
![image](https://user-images.githubusercontent.com/26005662/30684819-9a62f90e-9eaa-11e7-9e81-d192c19a2acc.png)

So, the gradle console does not have any output. Only the previous output:
```
====== STARTED GrabVer v0.4.0
INFO - ProjectName=app
...
BUILD SUCCESSFUL in 12s
25 actionable tasks: 7 executed, 18 up-to-date
```

**Comment by jrcacd** [comment]
I removed completely this library from gradle, run gradle clean, and then put the new version.
Problem resolved.
Now works!

**Comment by jrcacd** [comment]
Ahhh! The same error again!
Found what causes the error: 
Needs to have the preRelease line on gradle: 
```
versioning {
    ...
    preRelease = ''
}
```

If as bellow, gives the error
```
versioning {
    major = 0
    minor = 12
}
```

**Comment by davideas** [comment]
Delete from the cache the _jar file_, so the new version is forced to download and to be execute right there. I will try new tests in the coming days.

The 0.4.1 version should have `preRelease` optional now and not overwritten from the properties.

**Comment by jrcacd** [comment]
I already Invalidate Caches/Restart before.
How do I?
> Delete from the cache the jar file

**Comment by davideas** [comment]
You should have a `.gradle` folder somewhere probably under users, then, a subfolder named `file-xx`, in there you should see the repository with all groupIds, go under my group id eu/davidea, and clean the grabver folder.

**Comment by jrcacd** [comment]
Found it. Thanks.
But the error persists

**Comment by davideas** [comment]
I found the issue, strange that the unit tests don't catch it in the project.
It's a NPE when writing the file with null preRelease and the HashTable in the Properties class don't like indeed.

You can run `gradlew build --stacktrace` line 88.

**Comment by jrcacd** [comment]
Great!
