### ISSUE TITLE
Hosted in JCenter

### ISSUE THREAD

**Issue by barnhill** [davideas/GrabVer#30]
This project (used by FlexibleAdapter) needs to be moved from JCenter to Maven Central to prevent compilation problems.

**Comment by davideas** [comment]
Plugin is also available in Gradle plugin repository: https://plugins.gradle.org/m2/
Please ignore JCenter.

**Comment by barnhill** [comment]
Plugin repo just mirrors JCemter right?

**Comment by davideas** [comment]
I think I already claimed and used the gradle publish way when I created the plugin long time ago.
Try it, remove plugin from cache and then use the Gradle m2 repo.
