### ISSUE TITLE
Can the version.properties file be generated with the properties ordered?

### ISSUE THREAD

**Issue by jrcacd** [davideas/GrabVer#5]
**Atual**
```
#Thu Sep 21 15:02:01 BST 2017
CODE=0
MAJOR=0
PRE_RELEASE=
MINOR=12
BUILD=13
PATCH=2
```

**Ordened**
```
#Thu Sep 21 15:02:01 BST 2017
MAJOR=0
MINOR=12
PATCH=2
BUILD=13
PRE_RELEASE=
CODE=0
```

**Comment by davideas** [comment]
Properties is backed by an HashTable, so it keeps hashing ordering.
There are ways to have sorted hash with TreeMap, but is it a worth?

**Comment by jrcacd** [comment]
Organized is clearer

**Comment by davideas** [comment]
Build is after PreRelease: `1.0.0-RC1+build` ( and `Code` is for Android only).

I'm using https://bintray.com/etienne/java-utilities/java-ordered-properties.
To have ordered properties, you will need to save the content and after delete the file, then you will restore the values.
