### ISSUE TITLE
Patch is not being increased in release 

### ISSUE THREAD

**Issue by jrcacd** [davideas/GrabVer#6]
```
versioning {
    major = 0
    minor = 12
}
```

It generates:
```
#Mon Sep 25 10:04:58 BST 2017
CODE=0
MAJOR=0
MINOR=12
BUILD=17
PATCH=3
PRE_RELEASE=
```

If I delete the `PRE_RELEASE=` , it recreates it

**Comment by davideas** [comment]
Property `propPreRelease` is not in the calculation to determine the new patch. You can achieve the same when adding `grabverRelease` task or using the Android release task. This is the unit test for _release + no version_ change. 
``` text
====== Auto-generating content properties for test
====== STARTED GrabVer v0.5.0
INFO - ProjectName=test
INFO - runTasks=[grabverRelease]
INFO - Versioning Root Project 'test'
INFO - Versioning Filename: 'D:\Pgm\IntelliJIDEAProjects\GrabVer\version.properties'
INFO - Current versioning: 1.1.1 #20 code=3
INFO - Running with 'release' task: 'Code' version will auto increment
TEST - [Release + NoVersionChange]
INFO - Auto incrementing build number
INFO - Auto incrementing code version
INFO - Auto incrementing patch version
TEST - code=4
TEST - name=1.1.2
TEST - fullVersionName=1.1.2 #21 built on 2017.10.03
TEST - u1.1 - 1.1.2 #21 code=4
```

**Comment by jrcacd** [comment]
This ...
```
versioning {
    major = 0
    minor = 12
}
```

...when generate a apk, generates:
```
CODE=0
MAJOR=0
MINOR=12
BUILD=17
PATCH=3
PRE_RELEASE=
```

When gerarate an apk (again) It generates:
```
CODE=0
MAJOR=0
MINOR=12
BUILD=18
PATCH=3
PRE_RELEASE=
```

The patch, still is the same!!!

I thought this ocours becouse it generates the
`PRE_RELEASE=`

But, if that is ok, then, the patch not being increased error, still persists

**Comment by davideas** [comment]
@jrcacd, the patch is increased with `assembleRelease` task or with `grabverRelease` task. From Gradle window on the right double click on `assembleRelease` for the module you want.
Alternatively you can run via command line and run `gradlew assembleRelease -x test`.

At the moment gradle will execute release for all modules.

**Comment by jrcacd** [comment]
When I in Android Studio:
via menu build > Build APK (assembleDebug) | Generate signed APK (assembleRelease) 
it does not increase the patch number. (with the options above indicated)

**Comment by davideas** [comment]
@jrcacd, ahhh you know why? it puts `:<module_name>:assembleRelease` and not only `assembleRelease` 👎 

I will fix that.

**PS.** Do you want that when building APK also will increase it as it was a release or only for a real signed APK? I think only the last one, because for the first one we can add `grabverRelease` task name to force it.
I also added a `grabverSkip` it might come usefull in the future.

**Comment by jrcacd** [comment]
Very good, I agree.
only for a real signed APK

**Comment by dramixx** [comment]
Hi ! 

You changed `assembleRelease ` into `:<module_name>:assembleRelease` but when i launch the assembleRelease from Gradle window like you said, it launch just `assembleRelease` without the `:module_name:` ... So patch is not increased :( 
 Could you please add version increasing even the module_name does not appear ?

Thx a lot !

**Comment by davideas** [comment]
@dramixx, do you mean to have this condition?
``` gradle
runTasks.contains("grabverRelease") || 
runTasks.contains("assembleRelease") ||
runTasks.contains(":" + module + ":assembleRelease")
```
Now the condition is only:
``` gradle
runTasks.contains("grabverRelease") || 
runTasks.contains(":" + module + ":assembleRelease")
```

**Comment by jrcacd** [comment]
To finish #14 I think it only needs to add this: 
`runTasks.contains("bundle") || `

**Comment by dramixx** [comment]
@davideas Yes I think it would be better ;) !!
